# Generated by Django 5.0.7 on 2024-07-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_code_attendance', '0002_scannedqrcode_remove_class_students_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('attend', models.CharField(default='yes', max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='ScannedQRCode',
        ),
    ]
